apiVersion: v1
kind: Service
metadata:
  name: museum-wayang
spec:
  type: NodePort
  selector:
    app: museum-wayang
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002  # Port yang akan diakses di host (opsional)
