apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "web_chat"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - "localhost"
                - "-u"
                - "root"
                - "-proot"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: museum-wayang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: museum-wayang
  template:
    metadata:
      labels:
        app: museum-wayang
    spec:
      containers:
        - name: museum-wayang
          image: rotua10/uas-wayang:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m  # Minimum CPU request
            limits:
              cpu: 500m  # Maximum CPU limit
