apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: museum-wayang-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: museum-wayang
  minReplicas: 2 # merubah jumlah repika menjadi 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50